services:
  web:
    container_name: web
    build:
      context: ./web
      target: ${NODE_ENV} # envファイルで指定したイメージでコンテナを起動。ただし、変更を反映させるには、--buildをつけてビルドから始めること。
      args:
        - VITE_API_PORT=${API_PORT}
    depends_on:
      - api # apiサービスの起動後、webサービスを起動
    ports:
      - 80:80
    environment:
      - VITE_API_PORT=${API_PORT}
    volumes:
      - ./web:/app
      - web_node_modules:/app/node_modules # 名前付きボリュームとコンテナ側のnode_modulesを同期させる
    networks:
      - external_net # 外部との接続に利用するネットワーク
    
  api:
    container_name: api
    build:
      context: ./api
      target: ${NODE_ENV}
    depends_on:
      - db # dbサービスの起動後、apiサービスを起動
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      - NODE_ENV=${NODE_ENV}
      - API_PORT=${API_PORT}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./api:/app # apiソースコード全体をコンテナの/appにマウント
      - api_node_modules:/app/node_modules
    networks:
      - external_net
      - internal_net # dbサービスとの接続に利用するネットワーク
  
  db:
    container_name: db
    image: mysql:8.4.0
    restart: always # 停止すると自動的に再起動する
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    environment:
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql # mysql_dataボリュームを、mysqlの保存先ディレクトリにマウント
    networks:
      - internal_net

volumes:
  web_node_modules:
  api_node_modules:
  mysql_data:

networks:
  internal_net:
    internal: true # 内部ネットワークとして定義
  external_net: